//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nanoFramework.TestPlatform.MSTest.TestAdapter.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nanoFramework.TestPlatform.MSTest.TestAdapter.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Access string has invalid syntax..
        /// </summary>
        internal static string AccessStringInvalidSyntax {
            get {
                return ResourceManager.GetString("AccessStringInvalidSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The expected collection contains {1} occurrence(s) of &lt;{2}&gt;. The actual collection contains {3} occurrence(s). {0}.
        /// </summary>
        internal static string ActualHasMismatchedElements {
            get {
                return ResourceManager.GetString("ActualHasMismatchedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duplicate item found:&lt;{1}&gt;. {0}.
        /// </summary>
        internal static string AllItemsAreUniqueFailMsg {
            get {
                return ResourceManager.GetString("AllItemsAreUniqueFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expected:&lt;{1}&gt;. Case is different for actual value:&lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreEqualCaseFailMsg {
            get {
                return ResourceManager.GetString("AreEqualCaseFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expected a difference no greater than &lt;{3}&gt; between expected value &lt;{1}&gt; and actual value &lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreEqualDeltaFailMsg {
            get {
                return ResourceManager.GetString("AreEqualDeltaFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expected:&lt;{1} ({2})&gt;. Actual:&lt;{3} ({4})&gt;. {0}.
        /// </summary>
        internal static string AreEqualDifferentTypesFailMsg {
            get {
                return ResourceManager.GetString("AreEqualDifferentTypesFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expected:&lt;{1}&gt;. Actual:&lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreEqualFailMsg {
            get {
                return ResourceManager.GetString("AreEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expected a difference greater than &lt;{3}&gt; between expected value &lt;{1}&gt; and actual value &lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreNotEqualDeltaFailMsg {
            get {
                return ResourceManager.GetString("AreNotEqualDeltaFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expected any value except:&lt;{1}&gt;. Actual:&lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreNotEqualFailMsg {
            get {
                return ResourceManager.GetString("AreNotEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do not pass value types to AreSame(). Values converted to Object will never be the same. Consider using AreEqual(). {0}.
        /// </summary>
        internal static string AreSameGivenValues {
            get {
                return ResourceManager.GetString("AreSameGivenValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} failed. {1}.
        /// </summary>
        internal static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a async TestMethod with UITestMethodAttribute are not supported. Either remove async or use TestMethodAttribute..
        /// </summary>
        internal static string AsyncUITestMethodNotSupported {
            get {
                return ResourceManager.GetString("AsyncUITestMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MSTestAdapterV2.
        /// </summary>
        internal static string AttachmentSetDisplayName {
            get {
                return ResourceManager.GetString("AttachmentSetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Both collections are empty. {0}.
        /// </summary>
        internal static string BothCollectionsEmpty {
            get {
                return ResourceManager.GetString("BothCollectionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Both collection contain same elements..
        /// </summary>
        internal static string BothCollectionsSameElements {
            get {
                return ResourceManager.GetString("BothCollectionsSameElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Both collection references point to the same collection object. {0}.
        /// </summary>
        internal static string BothCollectionsSameReference {
            get {
                return ResourceManager.GetString("BothCollectionsSameReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Both collections contain the same elements. {0}.
        /// </summary>
        internal static string BothSameElements {
            get {
                return ResourceManager.GetString("BothSameElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Could not find file &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindFile {
            get {
                return ResourceManager.GetString("CannotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}({1}).
        /// </summary>
        internal static string CollectionEqualReason {
            get {
                return ResourceManager.GetString("CollectionEqualReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The parameter should not be null or empty..
        /// </summary>
        internal static string Common_CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Common_CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The parameter should not be null or empty..
        /// </summary>
        internal static string Common_CannotBeNullOrEmpty1 {
            get {
                return ResourceManager.GetString("Common_CannotBeNullOrEmpty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The parameter must be greater than zero..
        /// </summary>
        internal static string Common_MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Common_MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (null).
        /// </summary>
        internal static string Common_NullInMessages {
            get {
                return ResourceManager.GetString("Common_NullInMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (object).
        /// </summary>
        internal static string Common_ObjectString {
            get {
                return ResourceManager.GetString("Common_ObjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a String &apos;{0}&apos; does not contain string &apos;{1}&apos;. {2}..
        /// </summary>
        internal static string ContainsFail {
            get {
                return ResourceManager.GetString("ContainsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MSTestAdapter failed to discover tests in class &apos;{0}&apos; of assembly &apos;{1}&apos; because {2}..
        /// </summary>
        internal static string CouldNotInspectTypeDuringDiscovery {
            get {
                return ResourceManager.GetString("CouldNotInspectTypeDuringDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MSTestAdapter failed to discover tests in class &apos;{0}&apos; of assembly &apos;{1}&apos;. Reason {2}..
        /// </summary>
        internal static string CouldNotInspectTypeDuringDiscovery1 {
            get {
                return ResourceManager.GetString("CouldNotInspectTypeDuringDiscovery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} (Data Row {1}).
        /// </summary>
        internal static string DataDrivenResultDisplayName {
            get {
                return ResourceManager.GetString("DataDrivenResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} ({1}).
        /// </summary>
        internal static string DataDrivenResultDisplayName1 {
            get {
                return ResourceManager.GetString("DataDrivenResultDisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Debug Trace:.
        /// </summary>
        internal static string DebugTraceBanner {
            get {
                return ResourceManager.GetString("DebugTraceBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: Bad deployment item: &apos;{0}&apos;: output directory &apos;{1}&apos; specifies the item to be deployed outside deployment root directory which is not allowed..
        /// </summary>
        internal static string DeploymentErrorBadDeploymentItem {
            get {
                return ResourceManager.GetString("DeploymentErrorBadDeploymentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: Failed to access output directory &apos;{1}&apos; specified by deployment item &apos;{0}&apos;, the item will not be deployed: {2}: {3}.
        /// </summary>
        internal static string DeploymentErrorFailedToAccesOutputDirectory {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToAccesOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: Failed to access the file &apos;{0}&apos;: {1}: {2}.
        /// </summary>
        internal static string DeploymentErrorFailedToAccessFile {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: Failed to copy file &apos;{0}&apos; to &apos;{1}&apos;: {2}: {3}.
        /// </summary>
        internal static string DeploymentErrorFailedToCopyWithOverwrite {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToCopyWithOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: Failed to deploy dependencies for test storage &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string DeploymentErrorFailedToDeployDependencies {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToDeployDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: Failed to get the file for {0}: {1}: {2}.
        /// </summary>
        internal static string DeploymentErrorFailedToGetFileForDeploymentItem {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToGetFileForDeploymentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: an error occurred while getting satellite assemblies for {0}: {1}: {2}.
        /// </summary>
        internal static string DeploymentErrorGettingSatellite {
            get {
                return ResourceManager.GetString("DeploymentErrorGettingSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a deployment item &apos;{0}&apos;.
        /// </summary>
        internal static string DeploymentItem {
            get {
                return ResourceManager.GetString("DeploymentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid deployment item: the specified path &apos;{0}&apos; or output directory &apos;{1}&apos; contains illegal characters..
        /// </summary>
        internal static string DeploymentItemContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("DeploymentItemContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid deployment item: the output directory cannot be null..
        /// </summary>
        internal static string DeploymentItemOutputDirectoryCannotBeNull {
            get {
                return ResourceManager.GetString("DeploymentItemOutputDirectoryCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid deployment item: the specified output directory &apos;{0}&apos; is not relative..
        /// </summary>
        internal static string DeploymentItemOutputDirectoryMustBeRelative {
            get {
                return ResourceManager.GetString("DeploymentItemOutputDirectoryMustBeRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid deployment item: the path must contain at least one character..
        /// </summary>
        internal static string DeploymentItemPathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("DeploymentItemPathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a deployment item &apos;{0}&apos; (output directory &apos;{1}&apos;).
        /// </summary>
        internal static string DeploymentItemWithOutputDirectory {
            get {
                return ResourceManager.GetString("DeploymentItemWithOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [MSTest][Discovery][{0}] {1}.
        /// </summary>
        internal static string DiscoveryWarning {
            get {
                return ResourceManager.GetString("DiscoveryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assert.Equals should not be used for Assertions. Please use Assert.AreEqual &amp; overloads instead..
        /// </summary>
        internal static string DoNotUseAssertEquals {
            get {
                return ResourceManager.GetString("DoNotUseAssertEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Method {0} must match the expected signature: public static {1} {0}({2})..
        /// </summary>
        internal static string DynamicDataDisplayName {
            get {
                return ResourceManager.GetString("DynamicDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Property or method {0} on {1} does not return IEnumerable&lt;object[]&gt;..
        /// </summary>
        internal static string DynamicDataIEnumerableNull {
            get {
                return ResourceManager.GetString("DynamicDataIEnumerableNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value returned by property or method {0} shouldn&apos;t be null..
        /// </summary>
        internal static string DynamicDataValueNull {
            get {
                return ResourceManager.GetString("DynamicDataValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The number of elements in the collections do not match. Expected:&lt;{1}&gt;. Actual:&lt;{2}&gt;.{0}.
        /// </summary>
        internal static string ElementNumbersDontMatch {
            get {
                return ResourceManager.GetString("ElementNumbersDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Element at index {0} do not match..
        /// </summary>
        internal static string ElementsAtIndexDontMatch {
            get {
                return ResourceManager.GetString("ElementsAtIndexDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Element at index {1} is not of expected type. Expected type:&lt;{2}&gt;. Actual type:&lt;{3}&gt;.{0}.
        /// </summary>
        internal static string ElementTypesAtIndexDontMatch {
            get {
                return ResourceManager.GetString("ElementTypesAtIndexDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Element at index {1} is (null). Expected type:&lt;{2}&gt;.{0}.
        /// </summary>
        internal static string ElementTypesAtIndexDontMatch2 {
            get {
                return ResourceManager.GetString("ElementTypesAtIndexDontMatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a String &apos;{0}&apos; does not end with string &apos;{1}&apos;. {2}..
        /// </summary>
        internal static string EndsWithFail {
            get {
                return ResourceManager.GetString("EndsWithFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}: {1}.
        /// </summary>
        internal static string EnumeratorLoadTypeErrorFormat {
            get {
                return ResourceManager.GetString("EnumeratorLoadTypeErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid argument- EqualsTester can&apos;t use nulls..
        /// </summary>
        internal static string EqualsTesterInvalidArgs {
            get {
                return ResourceManager.GetString("EqualsTesterInvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot convert object of type {0} to {1}..
        /// </summary>
        internal static string ErrorInvalidCast {
            get {
                return ResourceManager.GetString("ErrorInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test &apos;{0}&apos; exceeded execution timeout period..
        /// </summary>
        internal static string Execution_Test_Timeout {
            get {
                return ResourceManager.GetString("Execution_Test_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to Create msdia Session COM HResult &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToCreateDiaSession {
            get {
                return ResourceManager.GetString("FailedToCreateDiaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to load msdia.
        /// </summary>
        internal static string FailedToLoadMsDia {
            get {
                return ResourceManager.GetString("FailedToLoadMsDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The internal object referenced is no longer valid..
        /// </summary>
        internal static string InternalObjectNotValid {
            get {
                return ResourceManager.GetString("InternalObjectNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid value &apos;{0}&apos; specified for &apos;Scope&apos;. Supported scopes are {1}..
        /// </summary>
        internal static string InvalidParallelScopeValue {
            get {
                return ResourceManager.GetString("InvalidParallelScopeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid value &apos;{0}&apos; specified for &apos;Workers&apos;. The value should be a non-negative integer..
        /// </summary>
        internal static string InvalidParallelWorkersValue {
            get {
                return ResourceManager.GetString("InvalidParallelWorkersValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The parameter &apos;{0}&apos; is invalid. {1}..
        /// </summary>
        internal static string InvalidParameterToAssert {
            get {
                return ResourceManager.GetString("InvalidParameterToAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The property {0} has type {1}; expected type {2}..
        /// </summary>
        internal static string InvalidPropertyType {
            get {
                return ResourceManager.GetString("InvalidPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid settings &apos;{0}&apos;. Unexpected XmlAttribute: &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidSettingsXmlAttribute {
            get {
                return ResourceManager.GetString("InvalidSettingsXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid settings &apos;{0}&apos;. Unexpected XmlElement: &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidSettingsXmlElement {
            get {
                return ResourceManager.GetString("InvalidSettingsXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MSTestAdapter encountered an unexpected element &apos;{0}&apos; in its settings &apos;{1}&apos;. Remove this element and try again..
        /// </summary>
        internal static string InvalidSettingsXmlElement1 {
            get {
                return ResourceManager.GetString("InvalidSettingsXmlElement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} Expected type:&lt;{1}&gt;. Actual type:&lt;{2}&gt;..
        /// </summary>
        internal static string IsInstanceOfFailMsg {
            get {
                return ResourceManager.GetString("IsInstanceOfFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a String &apos;{0}&apos; does not match pattern &apos;{1}&apos;. {2}..
        /// </summary>
        internal static string IsMatchFail {
            get {
                return ResourceManager.GetString("IsMatchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wrong Type:&lt;{1}&gt;. Actual type:&lt;{2}&gt;. {0}.
        /// </summary>
        internal static string IsNotInstanceOfFailMsg {
            get {
                return ResourceManager.GetString("IsNotInstanceOfFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a String &apos;{0}&apos; matches pattern &apos;{1}&apos;. {2}..
        /// </summary>
        internal static string IsNotMatchFail {
            get {
                return ResourceManager.GetString("IsNotMatchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning : A testsettings file or a vsmdi file is not supported with the MSTest V2 Adapter..
        /// </summary>
        internal static string LegacyScenariosNotSupportedWarning {
            get {
                return ResourceManager.GetString("LegacyScenariosNotSupportedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: The assembly or module &apos;{0}&apos; was not found. Reason: {1}.
        /// </summary>
        internal static string MissingDeploymentDependency {
            get {
                return ResourceManager.GetString("MissingDeploymentDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test Run deployment issue: The assembly or module &apos;{0}&apos; was not found..
        /// </summary>
        internal static string MissingDeploymentDependencyWithoutReason {
            get {
                return ResourceManager.GetString("MissingDeploymentDependencyWithoutReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No test data source specified. Atleast one TestDataSource is required with DataTestMethodAttribute..
        /// </summary>
        internal static string NoDataRow {
            get {
                return ResourceManager.GetString("NoDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No exception thrown. {1} exception was expected. {0}.
        /// </summary>
        internal static string NoExceptionThrown {
            get {
                return ResourceManager.GetString("NoExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The parameter &apos;{0}&apos; is invalid. The value cannot be null. {1}..
        /// </summary>
        internal static string NullParameterToAssert {
            get {
                return ResourceManager.GetString("NullParameterToAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Different number of elements..
        /// </summary>
        internal static string NumberOfElementsDiff {
            get {
                return ResourceManager.GetString("NumberOfElementsDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 
        ///      The constructor with the specified signature could not be found. You might need to regenerate your private accessor,
        ///      or the member may be private and defined on a base class. If the latter is true, you need to pass the type
        ///      that defines the member into PrivateObject&apos;s constructor.
        ///    .
        /// </summary>
        internal static string PrivateAccessorConstructorNotFound {
            get {
                return ResourceManager.GetString("PrivateAccessorConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 
        ///      The member specified ({0}) could not be found. You might need to regenerate your private accessor,
        ///      or the member may be private and defined on a base class. If the latter is true, you need to pass the type
        ///      that defines the member into PrivateObject&apos;s constructor.
        ///    .
        /// </summary>
        internal static string PrivateAccessorMemberNotFound {
            get {
                return ResourceManager.GetString("PrivateAccessorMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Running tests in any of the provided sources is not supported for the selected platform.
        /// </summary>
        internal static string SourcesNotSupported {
            get {
                return ResourceManager.GetString("SourcesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a String &apos;{0}&apos; does not start with string &apos;{1}&apos;. {2}..
        /// </summary>
        internal static string StartsWithFail {
            get {
                return ResourceManager.GetString("StartsWithFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to discover tests from assembly {0}. Reason:{1}.
        /// </summary>
        internal static string TestAssembly_AssemblyDiscoveryFailure {
            get {
                return ResourceManager.GetString("TestAssembly_AssemblyDiscoveryFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File does not exist: {0}.
        /// </summary>
        internal static string TestAssembly_FileDoesNotExist {
            get {
                return ResourceManager.GetString("TestAssembly_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TestContext cannot be Null..
        /// </summary>
        internal static string TestContextIsNull {
            get {
                return ResourceManager.GetString("TestContextIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TestContext Messages:.
        /// </summary>
        internal static string TestContextMessageBanner {
            get {
                return ResourceManager.GetString("TestContextMessageBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test method {0} was not found..
        /// </summary>
        internal static string TestNotFound {
            get {
                return ResourceManager.GetString("TestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MSTest Executor: Test Parallelization enabled for {0} (Workers: {1}, Scope: {2})..
        /// </summary>
        internal static string TestParallelizationBanner {
            get {
                return ResourceManager.GetString("TestParallelizationBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}_{1} {2}.
        /// </summary>
        internal static string TestRunName {
            get {
                return ResourceManager.GetString("TestRunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to load types from the test source &apos;{0}&apos;. Some or all of the tests in this source may not be discovered..
        /// </summary>
        internal static string TypeLoadFailed {
            get {
                return ResourceManager.GetString("TypeLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assembly Cleanup method {0}.{1} failed. Error Message: {2}. StackTrace: {3}.
        /// </summary>
        internal static string UTA_AssemblyCleanupMethodWasUnsuccesful {
            get {
                return ResourceManager.GetString("UTA_AssemblyCleanupMethodWasUnsuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assembly Initialization method {0}.{1} threw exception. {2}: {3}. Aborting test execution..
        /// </summary>
        internal static string UTA_AssemblyInitMethodThrows {
            get {
                return ResourceManager.GetString("UTA_AssemblyInitMethodThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Class Cleanup method {0}.{1} failed. Error Message: {2}. Stack Trace: {3}.
        /// </summary>
        internal static string UTA_ClassCleanupMethodWasUnsuccesful {
            get {
                return ResourceManager.GetString("UTA_ClassCleanupMethodWasUnsuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Class Initialization method {0}.{1} threw exception. {2}: {3}..
        /// </summary>
        internal static string UTA_ClassInitMethodThrows {
            get {
                return ResourceManager.GetString("UTA_ClassInitMethodThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Method {0}.{1} has wrong signature. The method must be static, public, does not return a value and should not take any parameter. Additionally, if you are using async-await in method then return-type must be Task..
        /// </summary>
        internal static string UTA_ClassOrAssemblyCleanupMethodHasWrongSignature {
            get {
                return ResourceManager.GetString("UTA_ClassOrAssemblyCleanupMethodHasWrongSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Method {0}.{1} has wrong signature. The method must be static, public, does not return a value and should take a single parameter of type TestContext. Additionally, if you are using async-await in method then return-type must be Task..
        /// </summary>
        internal static string UTA_ClassOrAssemblyInitializeMethodHasWrongSignature {
            get {
                return ResourceManager.GetString("UTA_ClassOrAssemblyInitializeMethodHasWrongSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TestCleanup method {0}.{1} threw exception. {2}: {3}..
        /// </summary>
        internal static string UTA_CleanupMethodThrows {
            get {
                return ResourceManager.GetString("UTA_CleanupMethodThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error calling Test Cleanup method for test class {0}: {1}.
        /// </summary>
        internal static string UTA_CleanupMethodThrowsGeneralError {
            get {
                return ResourceManager.GetString("UTA_CleanupMethodThrowsGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TestCleanup Stack Trace.
        /// </summary>
        internal static string UTA_CleanupStackTrace {
            get {
                return ResourceManager.GetString("UTA_CleanupStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data source &apos;{0}&apos; cannot be found in the test configuration settings.
        /// </summary>
        internal static string UTA_DataSourceConfigurationSectionMissing {
            get {
                return ResourceManager.GetString("UTA_DataSourceConfigurationSectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a --- End of inner exception stack trace ---.
        /// </summary>
        internal static string UTA_EndOfInnerExceptionTrace {
            get {
                return ResourceManager.GetString("UTA_EndOfInnerExceptionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The unit test adapter failed to connect to the data source or to read the data. For more information on troubleshooting this error, see &quot;Troubleshooting Data-Driven Unit Tests&quot; (http://go.microsoft.com/fwlink/?LinkId=62412) in the MSDN Library. Error details: {0}.
        /// </summary>
        internal static string UTA_ErrorDataConnectionFailed {
            get {
                return ResourceManager.GetString("UTA_ErrorDataConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA015: A generic method cannot be a test method. {0}.{1} has invalid signature.
        /// </summary>
        internal static string UTA_ErrorGenericTestMethod {
            get {
                return ResourceManager.GetString("UTA_ErrorGenericTestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA007: Method {1} defined in class {0} does not have correct signature. Test method marked with the [TestMethod] attribute must be non-static, public, return-type as void  and should not take any parameter. Example: public void Test.Class1.Test(). Additionally, if you are using async-await in test method then return-type must be Task. Example: public async Task Test.Class1.Test2().
        /// </summary>
        internal static string UTA_ErrorIncorrectTestMethodSignature {
            get {
                return ResourceManager.GetString("UTA_ErrorIncorrectTestMethodSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA031: class {0} does not have valid TestContext property. TestContext must be of type TestContext, must be non-static, public and must not be read-only. For example: public TestContext TestContext..
        /// </summary>
        internal static string UTA_ErrorInValidTestContextSignature {
            get {
                return ResourceManager.GetString("UTA_ErrorInValidTestContextSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA054: {0}.{1} has invalid Timeout attribute. The timeout must be a valid integer value and cannot be less than 0..
        /// </summary>
        internal static string UTA_ErrorInvalidTimeout {
            get {
                return ResourceManager.GetString("UTA_ErrorInvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA014: {0}: Cannot define more than one method with the AssemblyCleanup attribute inside an assembly..
        /// </summary>
        internal static string UTA_ErrorMultiAssemblyClean {
            get {
                return ResourceManager.GetString("UTA_ErrorMultiAssemblyClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA013: {0}: Cannot define more than one method with the AssemblyInitialize attribute inside an assembly..
        /// </summary>
        internal static string UTA_ErrorMultiAssemblyInit {
            get {
                return ResourceManager.GetString("UTA_ErrorMultiAssemblyInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA026: {0}: Cannot define more than one method with the ClassCleanup attribute inside a class..
        /// </summary>
        internal static string UTA_ErrorMultiClassClean {
            get {
                return ResourceManager.GetString("UTA_ErrorMultiClassClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA025: {0}: Cannot define more than one method with the ClassInitialize attribute inside a class..
        /// </summary>
        internal static string UTA_ErrorMultiClassInit {
            get {
                return ResourceManager.GetString("UTA_ErrorMultiClassInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA024: {0}: Cannot define more than one method with the TestCleanup attribute..
        /// </summary>
        internal static string UTA_ErrorMultiClean {
            get {
                return ResourceManager.GetString("UTA_ErrorMultiClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA018: {0}: Cannot define more than one method with the TestInitialize attribute..
        /// </summary>
        internal static string UTA_ErrorMultiInit {
            get {
                return ResourceManager.GetString("UTA_ErrorMultiInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA001: TestClass attribute defined on non-public class {0}.
        /// </summary>
        internal static string UTA_ErrorNonPublicTestClass {
            get {
                return ResourceManager.GetString("UTA_ErrorNonPublicTestClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA023: {0}: Cannot define predefined property {2} on method {1}..
        /// </summary>
        internal static string UTA_ErrorPredefinedTestProperty {
            get {
                return ResourceManager.GetString("UTA_ErrorPredefinedTestProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA022: {0}.{1}: The custom property &quot;{2}&quot; is already defined. Using &quot;{3}&quot; as value..
        /// </summary>
        internal static string UTA_ErrorTestPropertyAlreadyDefined {
            get {
                return ResourceManager.GetString("UTA_ErrorTestPropertyAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UTA021: {0}: Null or empty custom property defined on method {1}. The custom property must have a valid name..
        /// </summary>
        internal static string UTA_ErrorTestPropertyNullOrEmpty {
            get {
                return ResourceManager.GetString("UTA_ErrorTestPropertyNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exception thrown while executing test. If using extension of TestMethodAttribute then please contact vendor. Error message: {0}.
        /// </summary>
        internal static string UTA_ExecuteThrewException {
            get {
                return ResourceManager.GetString("UTA_ExecuteThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The ExpectedException attribute defined on test method {0}.{1} threw an exception during construction.
        ///{2}.
        /// </summary>
        internal static string UTA_ExpectedExceptionAttributeConstructionException {
            get {
                return ResourceManager.GetString("UTA_ExpectedExceptionAttributeConstructionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to obtain the exception thrown by test method {0}.{1}..
        /// </summary>
        internal static string UTA_FailedToGetTestMethodException {
            get {
                return ResourceManager.GetString("UTA_FailedToGetTestMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Initialization method {0}.{1} threw exception. {2}..
        /// </summary>
        internal static string UTA_InitMethodThrows {
            get {
                return ResourceManager.GetString("UTA_InitMethodThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to create instance of class {0}. Error: {1}..
        /// </summary>
        internal static string UTA_InstanceCreationError {
            get {
                return ResourceManager.GetString("UTA_InstanceCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Method {0}.{1} does not exist..
        /// </summary>
        internal static string UTA_MethodDoesNotExists {
            get {
                return ResourceManager.GetString("UTA_MethodDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The test method {0}.{1} has multiple attributes derived from ExpectedExceptionBaseAttribute defined on it. Only one such attribute is allowed..
        /// </summary>
        internal static string UTA_MultipleExpectedExceptionsOnTestMethod {
            get {
                return ResourceManager.GetString("UTA_MultipleExpectedExceptionsOnTestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to get default constructor for class {0}..
        /// </summary>
        internal static string UTA_NoDefaultConstructor {
            get {
                return ResourceManager.GetString("UTA_NoDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error in executing test. No result returned by extension. If using extension of TestMethodAttribute then please contact vendor..
        /// </summary>
        internal static string UTA_NoTestResult {
            get {
                return ResourceManager.GetString("UTA_NoTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to find property {0}.TestContext. Error:{1}..
        /// </summary>
        internal static string UTA_TestContextLoadError {
            get {
                return ResourceManager.GetString("UTA_TestContextLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to set TestContext property for the class {0}. Error: {1}..
        /// </summary>
        internal static string UTA_TestContextSetError {
            get {
                return ResourceManager.GetString("UTA_TestContextSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The {0}.TestContext has incorrect type..
        /// </summary>
        internal static string UTA_TestContextTypeMismatchLoadError {
            get {
                return ResourceManager.GetString("UTA_TestContextTypeMismatchLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Method {0}.{1} has wrong signature. The method must be non-static, public, does not return a value and should not take any parameter. Additionally, if you are using async-await in method then return-type must be Task..
        /// </summary>
        internal static string UTA_TestInitializeAndCleanupMethodHasWrongSignature {
            get {
                return ResourceManager.GetString("UTA_TestInitializeAndCleanupMethodHasWrongSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Only data driven test methods can have parameters. Did you intend to use [DataRow] or [DynamicData]?.
        /// </summary>
        internal static string UTA_TestMethodExpectedParameters {
            get {
                return ResourceManager.GetString("UTA_TestMethodExpectedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test method {0}.{1} threw exception: 
        ///{2}.
        /// </summary>
        internal static string UTA_TestMethodThrows {
            get {
                return ResourceManager.GetString("UTA_TestMethodThrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to get type {0}. Error: {1}..
        /// </summary>
        internal static string UTA_TypeLoadError {
            get {
                return ResourceManager.GetString("UTA_TypeLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}. If you are using UI objects in test consider using [UITestMethod] attribute instead of [TestMethod] to execute test in UI thread..
        /// </summary>
        internal static string UTA_WrongThread {
            get {
                return ResourceManager.GetString("UTA_WrongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The expected exception type must be System.Exception or a type derived from System.Exception..
        /// </summary>
        internal static string UTF_ExpectedExceptionTypeMustDeriveFromException {
            get {
                return ResourceManager.GetString("UTF_ExpectedExceptionTypeMustDeriveFromException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (Failed to get the message for an exception of type {0} due to an exception.).
        /// </summary>
        internal static string UTF_FailedToGetExceptionMessage {
            get {
                return ResourceManager.GetString("UTF_FailedToGetExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (Failed to get the message for an exception of type {0} due to an exception.).
        /// </summary>
        internal static string UTF_FailedToGetExceptionMessage1 {
            get {
                return ResourceManager.GetString("UTF_FailedToGetExceptionMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test method did not throw expected exception {0}. {1}.
        /// </summary>
        internal static string UTF_TestMethodNoException {
            get {
                return ResourceManager.GetString("UTF_TestMethodNoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test method did not throw an exception. An exception was expected by attribute {0} defined on the test method..
        /// </summary>
        internal static string UTF_TestMethodNoExceptionDefault {
            get {
                return ResourceManager.GetString("UTF_TestMethodNoExceptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test method threw exception {0}, but exception {1} was expected. Exception message: {2}.
        /// </summary>
        internal static string UTF_TestMethodWrongException {
            get {
                return ResourceManager.GetString("UTF_TestMethodWrongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test method threw exception {0}, but exception {1} or a type derived from it was expected. Exception message: {2}.
        /// </summary>
        internal static string UTF_TestMethodWrongExceptionDerivedAllowed {
            get {
                return ResourceManager.GetString("UTF_TestMethodWrongExceptionDerivedAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Threw exception {2}, but exception {1} was expected. {0}
        ///Exception Message: {3}
        ///Stack Trace: {4}.
        /// </summary>
        internal static string WrongExceptionThrown {
            get {
                return ResourceManager.GetString("WrongExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wrong number of objects for permutation. Should be greater than zero..
        /// </summary>
        internal static string WrongNumberOfObjects {
            get {
                return ResourceManager.GetString("WrongNumberOfObjects", resourceCulture);
            }
        }
    }
}
